export const CHANGE_ADDRESS = "CHANGE_ADDRESS";
export const CHANGE_BALANCE = "CHANGE_BALANCE";
export const CHANGE_DATA = "CHANGE_DATA ";
export const CHANGE_INDEX = "CHANGE_INDEX";
export const CHANGE_WINNER_NUMBER = "CHANGE_WINNER_NUMBER";
